### ISSUE TITLE
Request: FFZ Integration

### ISSUE THREAD

**Issue by dregimbal** [Alejo47/chat_pronouns_browser_extension#1]
It would be nice to have pronouns support built into the [FrankerFaceZ](https://www.frankerfacez.com/) extension

**Comment by Alejo47** [comment]
FFZ Support is planned, however this will be done later in a separate repository which will be created when that development starts.

**Comment by dregimbal** [comment]
Glad to see that FFZ integrated the "Pronouns" add-on! 👍
