### ISSUE TITLE
NET::ERR_CERT_DATE_INVALID error causing the extension to not work

### ISSUE THREAD

**Issue by techygrrrl** [Alejo47/chat_pronouns_browser_extension#17]
Looks like the SSL cert is invalid which is breaking the website and browser extension.

When choosing "proceed (unsafe)" to navigate to the website, it works but calls from the browser extension don't work so pronouns do not get displayed.

<img width="763" alt="image" src="https://user-images.githubusercontent.com/88961088/206926733-32a963db-b85e-45f0-b3f5-a5c3eea4f5f7.png">

**Comment by Alejo47** [comment]
Thanks for catching! Will fix once I'm back on my laptop in a bit

**Comment by Alejo47** [comment]
Certificates have now been updated, may take a bit for browser cache to clear, please allow up to one hour for it to udpate on your end. If you are still having issues after an hour feel free to re-open this issue

**Comment by techygrrrl** [comment]
Seems to be working now! 🙌
