### ISSUE TITLE
Funding/Donation leads to dead end

### ISSUE THREAD

**Issue by lumodon** [Alejo47/chat_pronouns_browser_extension#19]
Line 12:
https://github.com/Alejo47/chat_pronouns_browser_extension/blob/45516729a03910c87406c47bd7c64a5c147ba59b/.github/FUNDING.yml#L12C9-L12C38

![DeadFundingLink](https://github.com/Alejo47/chat_pronouns_browser_extension/assets/10302608/1e15e93b-26fe-4458-89cc-c7c0710c6c5b)

**Comment by Alejo47** [comment]
Apologies for this, haven't spend much time checking issues for a bit.
Just updated the link.
